# time in seconds to wait before cancelling the vote request
vote-time: 60
# distance in blocks between players to not charge for trading
distance-buffer: 50
# amount to charge per block between players
distance-price: 0.01
