name: UnitedPostalService
version: @version@
main: io.github.gabehowe.unitedpostalservice.UnitedPostalService
api-version: 1.16
depend: [ Vault ]
authors: [ GabrielHowe ]
description: Ships items over long distances, for a cost
website: gabehowe.github.io
